package com.byteslounge.slickrepo.test.sqlserver

import com.byteslounge.slickrepo.test.{IntegerVersionedRepositoryTest, SQLServerConfig}

class SQLServerIntegerVersionedRepositoryTest extends IntegerVersionedRepositoryTest(SQLServerConfig.config)