version: 2.1
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: cimg/openjdk:8.0.432
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build and test
          command: >
            sbt compile &&
            sbt coverage test coverageReport coveralls
#          command: >
#            sbt compile &&
#            sbt "project db2" docker &&
#            sbt "project itsetup" dockerComposeUp &&
#            sbt coverage test coverageReport coveralls &&
#            sbt alldbs:test &&
#            sbt "project itsetup" dockerComposeStop
