version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: ~/build
    steps:
      - checkout
      - run:
          name: Build and test
          command: >
            sbt compile &&
            sbt "project db2" docker &&
            sbt "project itsetup" dockerComposeUp &&
            sbt coverage test coverageReport coveralls &&
            sbt alldbs:test &&
            sbt "project itsetup" dockerComposeStop
